version: "3.9"
services:
    mysql:
        image: mysql:5.7
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: "redis" # Use a public Redis image to build the redis service
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis_local:/data